##########################################
## Сервис - projects-csgosnipepot-redis ##
##########################################
##  redis latest  ##
####################
## Оглавление
##  
##  1. Базовый образ и разработчики
##  2. Скопировать stateless-часть приложения в контейнер
##

# 1. Базовый образ и разработчики
FROM redis:latest
MAINTAINER German Manvelov <4gekkman@gmail.com>

# 2. Скопировать stateless-часть приложения в контейнер
COPY ["data", "/theproject/service/"]





